### ISSUE TITLE
ChatAdminRequiredError when scraping members from channel

### ISSUE THREAD

**Issue by davidwickerhf** [erfan4lx/Telegram-Channel-Member-Scraper#1]
When trying to scrape members from a Channel, I get the following error:
`telethon.errors.rpcerrorlist.ChatAdminRequiredError: Chat admin privileges are required to do that in the specified chat (for example, to send a message in a channel which is not yours), or invalid permissions used for the 
channel or group (caused by GetParticipantsRequest)`

The channel I tried scraping from is a public channel.
It might be because Telegram updated the API...
Is there a way around this? @erfan4lx

**Comment by erfan4lx** [comment]
Hello friend. You should have admin access to that channel you want scrap the members. If you don't have, You give this error

**Comment by davidwickerhf** [comment]
Oh alright thank you!
May I ask if you know of any method to scrape a channel's users when you are not an admin of that channel?
I'll close this issue then

**Comment by erfan4lx** [comment]
No I don't have idea because Telegram don't access to do this. Good luck man
