### ISSUE TITLE
not working

### ISSUE THREAD

**Issue by Yoko11111111** [erfan4lx/Telegram-Channel-Member-Scraper#6]
telethon.errors.rpcerrorlist.ApiIdInvalidError: The api_id/api_hash combination is invalid (caused by ImportBotAuthorizationRequest)

**Comment by Yoko11111111** [comment]
i did its still not working

**Comment by erfan4lx** [comment]
What's the error dude? send me text of error.

**Comment by Yoko11111111** [comment]
> What's the error dude? send me text of error.

???

telethon.errors.rpcerrorlist.ApiIdInvalidError: The api_id/api_hash combination is invalid (caused by ImportBotAuthorizationRequest)

1. Comment on this issue lol

**Comment by erfan4lx** [comment]
You put wrong api id and hash, use correct one.

**Comment by Yoko11111111** [comment]
> You put wrong api id and hash, use correct one.

No it was correct the problem solved automaticly after a few days. You cant use the api id and hash directly i guess

**Comment by erfan4lx** [comment]
Nice to hear that it solved.
